# Title of your website
title: 'Stampaggio lamiera e lastratura mercato automotive - LASIM'
description: "Dal 1972 Lasim persegue l'obiettivo della soddisfazione dei Clienti attraverso l'innovazione e il miglioramento continuo."
url: "https://www.lasim.it"
# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]